Create a random tensor with shape (7, 7).

In [ ]:
import torch
import random
# Create a random tensor of size (7, 7)
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.1224, 0.0062, 0.8927, 0.0487, 0.3684, 0.6206, 0.6318],
         [0.6041, 0.2527, 0.4728, 0.8083, 0.9712, 0.0087, 0.6115],
         [0.1591, 0.4681, 0.5237, 0.3670, 0.2252, 0.3006, 0.2714],
         [0.4020, 0.8884, 0.4128, 0.1452, 0.7504, 0.8491, 0.7432],
         [0.1277, 0.6663, 0.8539, 0.0437, 0.9333, 0.4018, 0.7879],
         [0.6182, 0.5840, 0.3419, 0.7736, 0.3404, 0.2413, 0.5206],
         [0.9980, 0.8512, 0.4604, 0.6914, 0.9883, 0.5789, 0.0192]]),
 torch.Size([7, 7]))

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
# Create a random tensor of size (1, 7)
random_tensor1 = torch.rand(size=(1, 7))
random_tensor1 = random_tensor1.T

result = torch.matmul(random_tensor, random_tensor1)
result, result.shape

(tensor([[2.9138],
         [2.2021],
         [2.4702],
         [1.2455],
         [3.3136],
         [1.9538],
         [2.4030]]),
 torch.Size([7, 1]))

Set the random seed to 0 and do exercises 2 & 3 over again.

In [ ]:
#Setando a Random_Seed como zero
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)
#Criando os Tensores aleatórios
random_tensor_1 = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)
#Transpondo o tensor 2 para fazer uma multiplicação
random_tensor2 = random_tensor1.T
#Fazendo a multiplicação
result = torch.matmul(random_tensor, random_tensor1)
result, result.shape

tensor([[2.0771],
        [2.6047],
        [2.1881],
        [2.6202],
        [1.9160],
        [2.0793],
        [2.6524]])

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
#Testando se o torch está usando meus CUDA cores
#BTW, agora seria uma hora boa de ter uma GPU Nvidia
#Talvez dê pra brincar depois com isso
torch.cuda.is_available()

# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to('cuda')
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [ ]:
#Setando a Random_Seed como zero
RANDOM_SEED=1234
torch.manual_seed(seed=RANDOM_SEED)
#Criando os Tensores aleatórios
tensor = torch.rand(2, 3)

#Mandando eles para a GPU
tensor_on_gpu = tensor.to('cuda')
tensor_on_gpu

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [ ]:
#Setando a Random_Seed como zero
RANDOM_SEED=1234
torch.manual_seed(seed=1234)
#Criando os Tensores aleatórios
tensor_One = torch.rand(2, 3)
tensor_Two = torch.rand(2, 3)

#Mandando eles para a GPU
tensor_on_gpu_One = tensor_One.to('cuda')
tensor_on_gpu_Two = tensor_Two.to('cuda')
print(f"Tensor 1:\n{tensor_on_gpu_One}\n")
print(f"Tensor 2:\n{tensor_on_gpu_Two}\n")

Tensor 1:
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

Tensor 2:
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
#Mandando eles para a GPU
tensor_on_gpu_Two = tensor_on_gpu_Two.T

#Professor, por algum motivo, as vezes vai. as vezes não;
tensor_result = torch.mul(tensor_on_gpu_One, tensor_on_gpu_Two)
print(tensor_result)

tensor([[0.0015, 0.1881, 0.1751],
        [0.1215, 0.0457, 0.3945]], device='cuda:0')


Find the maximum and minimum values of the output of 7.

In [ ]:
print(f"Minimo: {tensor_result.min()}")
print(f"Maximo: {tensor_result.max()}")
print(f"Soma: {tensor_result.sum()}")

Minimo: 0.0015010491479188204
Maximo: 0.3945072591304779
Soma: 0.9264557957649231


Find the maximum and minimum index values of the output of 7.

In [ ]:
print(f"Minimo: {tensor_result.argmin()}")
print(f"Maximo: {tensor_result.argmax()}")

Minimo: 0
Maximo: 5


Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
# Create a random tensor of size (1, 7)
random_tensor_UNO = torch.rand(size=(1, 1, 1, 10))
print(f"Previous tensor: {random_tensor_UNO}")
print(f"Previous shape: {random_tensor_UNO.shape}")

#Squeeze
Uno_squeezed = random_tensor_UNO.squeeze()
print(f"\nNew tensor: {Uno_squeezed}")
print(f"New shape: {Uno_squeezed.shape}")

Previous tensor: tensor([[[[0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451,
           0.4966, 0.7865]]]])
Previous shape: torch.Size([1, 1, 1, 10])

New tensor: tensor([0.6839, 0.7658, 0.9149, 0.3993, 0.1100, 0.2541, 0.4333, 0.4451, 0.4966,
        0.7865])
New shape: torch.Size([10])
